# Generated by Django 3.1.6 on 2021-03-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_causer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.FileField(blank=True, upload_to='product_img'),
        ),
    ]
