# Generated by Django 3.1.6 on 2021-03-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20210315_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_addr',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
